### ISSUE TITLE
Mat读取

### ISSUE THREAD

**Issue by chasentech** [Jack-Cherish/VideoCapture#1]
我看了一下程序，发现读取图像信息用的是OpenCV1.0中的IplImage，我试着用Mat读取了一下，感觉速度还行，我想问一下，为什么不用Mat类读取呢？是不是速度会慢呢？

**Comment by Jack-Cherish** [comment]
@myzcl 这个没有测试过，你可以测一下读一耗时多久，用个函数即可。我是当时习惯用IplImage
